In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,5,8,9,6]])   # creating a numpy array

In [3]:
myarr

array([[1, 2, 5, 8, 9, 6]])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr.shape

(1, 6)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1]

2

In [8]:
myarr[0,1] = 56

In [9]:
myarr

array([[ 1, 56,  5,  8,  9,  6]])

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.size

9

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.dtype

dtype('int32')

In [16]:
zeroes = np.zeros((5,5))   # create the 5*5 matrix of zeroes

In [17]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeroes.dtype

dtype('float64')

In [19]:
zeroes.shape

(5, 5)

In [21]:
rangearray = np.arange(20)   # give the within specific range

In [22]:
rangearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
linspace = np.linspace(1,20,10)  # it will give 10 element between 1 to 20 which having equal difference betwteen each two element

In [41]:
linspace

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [48]:
empty = np.empty((2,4))  # it will return random element of 2*4 matrix

In [51]:
empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.85763116e-321, 3.11525958e-307,
        1.24610723e-306]])

In [52]:
identity = np.identity(10) # it will return 10*10 digonal matrix

In [53]:
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
identity.shape

(10, 10)

In [59]:
arr = np.arange(50)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
arr = arr.reshape(2,25)

In [77]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
arr.shape

(2, 25)

In [79]:
arr = arr.ravel() # it will convert pervious matrix into 1d array

In [80]:
arr.shape

(50,)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [82]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
ar.sum(axis = 0)

array([12, 15, 18])

In [85]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [87]:
ar.flat              # it is used for looping
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [89]:
myarr.ndim

2

In [90]:
arr.ndim

1

In [91]:
ar.ndim

2

In [92]:
onedarray = np.array([1,5,45,456,45698,123])

In [96]:
onedarray.argmax()  # largest element at 4th index

4

In [97]:
onedarray.argmin()  # minimunm element at 0th index

0

In [98]:
onedarray.argsort()   # it will sort the index by index 

array([0, 1, 2, 5, 3, 4], dtype=int64)

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
ar+listarray

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [103]:
ar*listarray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [104]:
ar*ar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [105]:
ar.sum()

45

In [110]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [113]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [115]:
np.count_nonzero(ar)

9